### ISSUE TITLE
Benachrichtigung -> leere Message

### ISSUE THREAD

**Issue by m-s-b** [iobroker-community-adapters/ioBroker.iceroad#15]
Egal ob ich Pushover oder Telegram in den Benachrichtigungen auswähle bekomme ich nur:
```
Error from Pushover: message cannot be blank <br>
Cannot send message [chatId - XXXXXXX]: Error: ETELEGRAM: 400 Bad Request: message text is empty
```
Zu dem Zeitpunkt müsste die Meldung "Eis!" kommen. 
Edit: Auch bei "kein Eis." ist die Message leer.

**Comment by ciddi89** [comment]
Hallo @m-s-b,
leider haut da eine Funktion nicht so hin. Habe diese erstmal auskommentiert und Nachrichten sollten nun wieder gesendet werden. Werde mich mal die Tage mit dem Adapter beschäftigen, finde die Idee nämlich ganz gut. Vielleicht kann man noch was verändern/verbessern?

**Comment by m-s-b** [comment]
@ciddi89 
Sauber, Test Messages kommen an und auch wenn man den Adapter startet. Im Log auch keine Fehler.
Als weitere Optimierung könnte man den Inhalt von "forecastText" in die Nachricht mit reinpacken?!?
Fehler ist meiner Meinung nach dann gefixt. Zu machen oder willst du die "Verbesserung" noch einbringen?

**Comment by ciddi89** [comment]
Okay, ja lass mal das issue solange auf. Ich schließe es dann wenn es mit den Text erledigt ist. Muss nur überlegen wie ich es am besten umsetze im Bezug mit den selbst eingestellten Text in den Instanz Einstellungen.

**Comment by m-s-b** [comment]
Hab den jetzt mal hier beim Eis-Wechsel in Betrieb gehabt, sobald "Eis" vorhanden ist schickt er im Abrufintervall die Meldung, ist etwas nervig/unnötig. 
Meiner Meinung nach wäre es optimal in den Einstellungen einen Messagetext für "Eis" und einen für "kein Eis" zu vergeben. Dieser wird dann beim Wechsel vom einem zum anderen geschickt und nicht immer im Abrufintervall.
Die Frage ist wenn mehrere Tage "Eis" ist, ob man dann 1x täglich morgens (konfigurierbar?!?) nochmals die Meldung bekommt.
Wenn VW mal die Server konitnuierlich ans Laufen bekommt könnte man daraus glatt ne automatische Scheibenentfrostung aufbauen :-D

**Comment by ciddi89** [comment]
habe es erstmal so gemacht das die Nachrichten nur bei state change gesendet werden. Aber derzeit nur den Text Eis oder Kein Eis. Ich muss die Tage den kompletten Code mal überarbeiten. Da ist einiges was mir so nicht passt. Würde es dann auch so machen das man im Admin seine eigene Texte wählen kann für Eis und Kein Eis, wenn man aber nichts eingetragen hat der Standart Text gesendet wird. Oder hast eine bessere Idee?

**Comment by m-s-b** [comment]
Mal schauen wann hier wieder ein State change kommt, sieht erstmal ziemlich frostig aus...
Wenn man nix eigenes hinterlegt ist der Standardtext doch völlig ausreichend. 
Eine Option 1x am Tag um x Uhr bei konstant anstehender Eiswarnung ne Meldung zu bekommen wäre ggf. nicht schlecht.

**Comment by ciddi89** [comment]
Ja, will evtl. vorher die Admin Oberfläche bearbeiten und umstellen auf JSON config. Danach/dabei füge ich die Option mit ein.

**Comment by ciddi89** [comment]
Hi, ich weiß nicht ob du schon die neue Version hast. Da es mit einer Uhrzeit im shedule Adapter nicht so gut zu lösen ist, da man Gefahr läuft das man die Zeit nicht erreicht, habe ich als Kompromiss eine Erinnerungsfunktion nach X Stunden falls Eis/vielleicht Eis ansteht, eine Nachricht senden, mit reingenommen. Leider gibst hier aber keine Eiswarnung mehr um das zu testen 😬

Außerdem ist der Adapter nun in der stable repo und kann darüber geupdatet werden. :)

**Comment by m-s-b** [comment]
Hi, ja, hab ich nur "leider" ist hier momentan auch kein Eis, kann daher nicht sagen ob x Stunden funktioniert oder nicht ;-)
