### ISSUE TITLE
Fehlermeldung Axios

### ISSUE THREAD

**Issue by Chaot1** [iobroker-community-adapters/ioBroker.iceroad#16]
Ich bekomme manchmal den Fehler:
`<html>
<body>

iceroad.0 | 2022-11-27 12:00:17.132 | error | 0.error:AxiosError: timeout of 5000ms exceeded
-- | -- | -- | --

</body>
</html>`

**Comment by ciddi89** [comment]
@Chaot1 habe den timeout von 5000 auf 10000 erhöht. Evtl. bleibt die Nachricht nun aus?
