### ISSUE TITLE
Instance already running

### ISSUE THREAD

**Issue by m-s-b** [iobroker-community-adapters/ioBroker.iceroad#4]
Hi,
ich habe scheinbar ein Problem mit dem beenden des Dienstes, bekomme regelmäßig die Meldung
`instance system.adapter.iceroad.0 already running with pid 66387`
Adapter auch schon komplett de- und neuistalliert.

**Comment by liv-in-sky** [comment]
habe das selbe problem

**Comment by Apollon77** [comment]
Please recheck with GitHub version

**Comment by m-s-b** [comment]
@Apollon77 
Looks fine. Last 2 requests as desired. When @liv-in-sky can confirm also i'll Close the issue.
Thanks

**Comment by liv-in-sky** [comment]
yes - it is working

**Comment by liv-in-sky** [comment]
thanx to @Apollon77

**Comment by Apollon77** [comment]
I will release later and pack it into latest
