### ISSUE TITLE
Add missung Values

### ISSUE THREAD

**Issue by Siggi0904** [iobroker-community-adapters/ioBroker.iceroad#6]
Hi,
refer to API, please add missing Values and make them configurable:
See: https://www.eiswarnung.de/rest-api/

URL: [https://api.eiswarnung.de?key=](https://api.eiswarnung.de/?key=)<KEY>&lat=<GPS_LAT>&lng=<GPS_LNG>

GPS-Data could be used from IOBroker values

code zahl -> Statuscode (200=Aufruf erfolgreich; 300=Geokoordinaten fehlen; 400=API Key fehlt; 401=API Key ungültig; 402=Tägliches Call-Limit erreicht)

success boolean -> War die Anfrage erfolgreich?
message string -> Fehler- oder Erfolgsmeldung
callsLeft zahl -> Für heute übrige Abfragen
callsDailyLimit zahl -> Tägliches Kontingent an API Abfragen
callsResetInSeconds zahl -> Sekunden bis zum nächsten Tag und Auffrischung des Kontingents

requestDate string (YYYY-mm-dd HH:ii:ss) -> Zeitpunkt der Anfrage
forecastId zahl -> Vorhersage 0 = kein Eis, 1 = Eis, 2 = evtl. Eis
forecastText string -> Vorhersage in Worten
forecastCity string -> Erkannter Ort zu den Geokoordinaten
forecastDate string -> Tag, für welchen die Vorhersage gültig ist

**Comment by Apollon77** [comment]
should be all in already
